---
title: "Exploration of clinical trial locations"
author: "Carrie Bennette"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
bs_theme: "cosmo"
params:
  date: "July 6, 2020"
---

Git hash: `r git2r::branch_target(git2r::head(git2r::repository(getwd())))`

[GitHub repo](https://github.com/CBennette-IDM/COVID_clinical_trial_locations)

```{r setup, include=FALSE}
# load libraries
library(tidyr)
library(RPostgreSQL)
library(dbplyr)
library(plyr)
library(dplyr)
library(stringr)
library(lubridate)
library(ggplot2)
library(cowplot)
library(tidycensus)
library(covdata)
library(DescTools)
library(zipzcta)
library(zcta)
library(sf)
library(maptools)
library(sp)
library(spdep)
library(INLA)
library(kableExtra)
library(pscl)
library(boot)
library(glmmTMB)

# options
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE) 
knitr::opts_chunk$set(fig.width=10, fig.height=5, fig.align = "center") 
options(scipen=10000)

```

```{r prep, include = FALSE, cache = TRUE}
#### PREP DATA ####

# Load multiple data sources 
# 1) clinical trial data from Cytel's clinical trial tracker, which is a nicely cleaned up list of all COVID19 trials derived from clinicaltrial.gov (and other sources for international trials)
# 2) zip codes of trials from AACT, which is the gold standard for cleaned up data from clinicaltrials.gov; doesn't have some of the more nuanced fields that Cytel's tracker does, but it includes zip codes of all trial location
# 3) Census-based demographic information
# 4) county-level case counts from NYTimes (via covdata package)
# 5) hospital data (individual aggregated to county-level) from Medicare/CMS
# 6) universities (https://hifld-geoplatform.opendata.arcgis.com/datasets/colleges-and-universities)

# load Cytel tracker data (downloaded from their website: )
trials <- read.csv("table_trials - 2020-07-08.csv") %>%
  filter(Country == "United States") %>%
  select(-Province) %>% 
  rename(nct_id = ID)

### AACT: oh how I've missed SQL databases
drv <- dbDriver('PostgreSQL')
con <- dbConnect(drv, 
                 dbname="aact",
                 host="aact-db.ctti-clinicaltrials.org", 
                 port=5432, 
                 user="cb11", 
                 password="idmuse")

# details of studies
study_tbl <- tbl(src=con,'studies')

# get locations
location_tbl <- tbl(src=con,'facilities')
locations <- location_tbl %>% 
  #filter(country == "United States") %>% DO NOT FILTER HERE (need to count non-US sites first)
  select(nct_id, zip) %>%
  collect()

# locations for covid trials only
trial_locations <- trials %>% 
  left_join(locations, by = "nct_id") %>%
  group_by(nct_id) %>%
  mutate(no_locations = n_distinct(zip, Country)) %>%
  ungroup() %>%
  filter(!is.na(zip) & Country == "United States") %>%
  mutate(zip = ifelse(nchar(zip) == 10, substr(zip, 1, 5), zip))

# load census data 
source("census_data.R")

# get urban designation (also from census, but outside tidycensus)
urban <- read.csv("PctUrbanRural_County.csv", header = TRUE) %>%
  mutate(geoid = as.double(paste0(ï..STATE, COUNTY))) %>%
  select(geoid, POPPCT_URBAN)

# load hospital data
hospitals <- read.csv("Hospitals.csv") %>%
  mutate(BEDS = ifelse(BEDS == -999, NA, BEDS)) %>%
  group_by(COUNTYFIPS) %>%
  summarise(hospitals = n(),
            hospital_beds = sum(BEDS)) %>%
  mutate(geoid = as.double(COUNTYFIPS))

# load university data
universities <- read.csv("Colleges_and_Universities.csv") %>%
  mutate(TOT_ENROLL = ifelse(TOT_ENROLL == -999, NA, TOT_ENROLL)) %>%
  filter(NAICS_DESC == "COLLEGES, UNIVERSITIES, AND PROFESSIONAL SCHOOLS") %>%
  filter(CLOSE_DATE == "-2") %>%
  group_by(COUNTYFIPS) %>%
  summarise(universities = n(),
            student_enrollment = sum(TOT_ENROLL)) %>%
  mutate(geoid = as.double(COUNTYFIPS))

# count trials per zip
# need to group by county; zips aren't as relevant here (plus we're merging with case data)
one_to_one_area = zcta::zcta_county_rel_10 %>% 
  select(zcta5, state, state, county, geoid, poppt, zpoppct, zareapct) %>% 
  group_by(zcta5) %>% 
  slice(which.max(zareapct))

#### note there are a handful of zip codes that don't match via this program; have manually reviewed these:
missing_zip <- read.csv("missing_zip.csv", as.is = TRUE) %>%
  mutate(geoid = as.double(geoid))

one_to_one_area <- one_to_one_area %>% 
  select(zcta5, geoid) %>%
  rbind(missing_zip)

trial_counts <- trial_locations %>%
  left_join(one_to_one_area %>% select(zcta5, geoid), by = c("zip" = "zcta5")) %>%
  distinct(nct_id, geoid, .keep_all = TRUE)

cases <- nytcovcounty %>%
  mutate(fips = ifelse(county == "New York City", "36061", fips)) 

### monthly estimates ###
trial_counts_month <- trial_counts %>%
  filter(!is.na(geoid)) %>%
  mutate(start = as.Date(paste0(Date, "-01"), "%Y-%B-%d"),
         end = as.Date(paste0(Completion, "-01"), "%Y-%B-%d"),
         march = start < '2020-03-31' & end >= '2020-03-01',
         april = start < '2020-04-30' & end >= '2020-04-01',
         may = start < '2020-05-31' & end >= '2020-05-01',
         june = start < '2020-06-30' & end >= '2020-06-01') %>%
  group_by(geoid) %>%
  mutate(total_march = sum(march, na.rm = T),
         total_april = sum(april, na.rm = T),
         total_may = sum(may, na.rm = T),
         total_june = sum(june, na.rm = T),
         enrollment_march = sum(ifelse(march == 1, Size/(max(as.numeric(end-start), 1)/30.5)/no_locations, 0), na.rm = T),
         enrollment_april = sum(ifelse(april == 1, Size/(max(as.numeric(end-start), 1)/30.5)/no_locations, 0), na.rm = T),
         enrollment_may = sum(ifelse(may == 1, Size/(max(as.numeric(end-start), 1)/30.5)/no_locations, 0), na.rm = T),
         enrollment_june = sum(ifelse(june == 1, Size/(max(as.numeric(end-start), 1)/30.5)/no_locations, 0), na.rm = T)) %>%
  ungroup() %>%
  select(geoid, total_march, total_april, total_may, total_june, enrollment_march, enrollment_april, enrollment_may, enrollment_june)

trial_new_month <- trial_counts %>%
  mutate(month = month(as.Date(paste0(Date, "-01"), "%Y-%B-%d"))) %>%
  group_by(geoid, month) %>%
  summarise(total = n()) %>%
  pivot_wider(names_from = month, values_from = total) %>%
  mutate(launched_march = ifelse(is.na(`3`), 0, `3`),
         launched_april = ifelse(is.na(`4`), 0, `4`),
         launched_may = ifelse(is.na(`5`), 0, `5`),
         launched_june = ifelse(is.na(`6`), 0, `6`)) %>%
  select(geoid, launched_march, launched_april, launched_may, launched_june)

cases_month <- cases %>%
  mutate(month = month(date)) %>%
  group_by(fips, month) %>%  
  summarise(cases_month = max(cases, na.rm = T)) %>%
  pivot_wider(names_from = month, values_from = cases_month) %>%
  mutate(cases_march = ifelse(is.na(`3`), 0, `3`),
         cases_april = ifelse(is.na(`4`), 0, `4`) - cases_march, # want incremental case counts
         cases_may = abs(ifelse(is.na(`5`), 0, `5`) - cases_april),
         cases_june = abs(ifelse(is.na(`6`), 0, `6`) - cases_may)) %>%
  select(fips, cases_march, cases_april, cases_may, cases_june) %>%
  mutate(geoid = fips)

trials <- cases_month %>%
  mutate(geoid = as.double(geoid)) %>%
  left_join(trial_counts_month, by = "geoid") %>%
  left_join(trial_new_month, by = "geoid")

trials_census <- census_clean %>%
  mutate(geoid = as.double(GEOID)) %>%
  left_join(urban, by = "geoid") %>%
  left_join(hospitals, by = "geoid") %>%
  left_join(universities, by = "geoid") %>%
  left_join(trials, by = "geoid") %>%
  mutate(total_march = ifelse(is.na(total_march), 0, total_march),
         total_april = ifelse(is.na(total_april), 0, total_april),
         total_may = ifelse(is.na(total_may), 0, total_may),
         total_june = ifelse(is.na(total_june), 0, total_june),
         launched_march = ifelse(is.na(launched_march), 0, launched_march),
         launched_april = ifelse(is.na(launched_april), 0, launched_april),
         launched_may = ifelse(is.na(launched_may), 0, launched_may),
         launched_june = ifelse(is.na(launched_june), 0, launched_june),
         enrollment_march = ifelse(is.na(enrollment_march), 0, enrollment_march),
         enrollment_april = ifelse(is.na(enrollment_april), 0, enrollment_april),
         enrollment_may = ifelse(is.na(enrollment_may), 0, enrollment_may),
         enrollment_june = ifelse(is.na(enrollment_june), 0, enrollment_june),
         hospitals = ifelse(is.na(hospitals), 0, hospitals),
         hospital_beds = ifelse(is.na(hospital_beds), 0, hospital_beds),
         universities = ifelse(is.na(universities), 0, universities),
         cases_march = ifelse(is.na(cases_march), 0, cases_march),
         cases_april = ifelse(is.na(cases_april), 0, cases_april),
         cases_may = ifelse(is.na(cases_may), 0, cases_may),
         cases_june = ifelse(is.na(cases_june), 0, cases_june),
         cases = cases_march + cases_april + cases_may + cases_june,
         total = total_march + total_april + total_may + total_june) %>%
  distinct() %>%
  mutate(state = substring(GEOID, 1, 2)) %>%
  filter(state != 72) # remove puerto rico


```


```{r crosstabs}

## number of counties, number of individuals, and number of cases:
CrossTab <- function(data, case, trial){
  case_no_trial <- data %>%
    filter({{case}} > 0 & {{trial}} == 0) %>%
    summarise(name = "Cases + no trials",
              county = n(),
              cases = mean({{case}})*n(),
              pop = mean(population)*n())
  case_trial <- data %>%
    filter({{case}} > 0 & {{trial}} > 0) %>%
    summarise(name = "Cases + trials",
              county = n(),
              cases = mean({{case}})*n(),
              pop = mean(population)*n())
  
  
  no_case_trial <- data %>%
    filter({{case}} == 0 & {{trial}} > 0) %>%
    summarise(name = "No cases + trials",
              county = n(),
              cases = mean({{case}})*n(), #NA
              pop = mean(population)*n()) #NA
  
  no_case_no_trial <- data %>%
    filter({{case}} == 0 & {{trial}} == 0) %>%
    summarise(name = "No cases + no trials",
              county = n(),
              cases = mean({{case}})*n(), #NA
              pop = mean(population)*n()) 

  cross_tab <- rbind(case_no_trial, 
                   case_trial, 
                   no_case_trial, 
                   no_case_no_trial)
  
  return(cross_tab)
}

CrossTab(trials_census, cases, total)

### also want to see the cross tab table by month:
CrossTab(trials_census, cases_march, total_march)
CrossTab(trials_census, cases_april, total_april)
CrossTab(trials_census, cases_may, total_may)
CrossTab(trials_census, cases_june, total_june)

# and what proportion of the cases without trials are in counties with 100+ cases
# 100+ cases in June?
high_pop <- trials_census %>% filter(cases > 1000 & total == 0) %>% summarise(sum = sum(cases))
low_pop <- trials_census %>% filter(cases <= 1000 & total == 0) %>% summarise(sum = sum(cases))

high_pop/(high_pop+low_pop)

june_high_pop <- trials_census %>% filter(cases_june > 100 & total == 0) %>% summarise(sum = sum(cases_june))
june_low_pop <- trials_census %>% filter(cases_june <= 100 & total == 0) %>% summarise(sum = sum(cases_june))

june_high_pop/(june_high_pop+june_low)
```

```{r gini}
# Gini coefficients
gini_total <- rbind(c("march", Gini(trials_census$total_march, trials_census$cases_march)),
              c("april", Gini(trials_census$total_april, trials_census$cases_april)),
              c("may", Gini(trials_census$total_may, trials_census$cases_may)),
              c("june", Gini(trials_census$total_june, trials_census$cases_june)))
gini_total

# look at persistence over time; just trials launched by month (taking out trials that remained open for months)
gini_new <- rbind(c("march", Gini(trials_census$launched_march, trials_census$cases_march)),
              c("april", Gini(trials_census$launched_april, trials_census$cases_april)),
              c("may", Gini(trials_census$launched_may, trials_census$cases_may)),
              c("june", Gini(trials_census$launched_june, trials_census$cases_june)))
gini_new

```

```{r models}

first_date <- cases %>%
  group_by(fips) %>%  
  summarise(date = min(date),
            days = today() - date)

trials_model <- trials_census %>%
  left_join(first_date, by = c("GEOID" = "fips")) %>%
  mutate(days = ifelse(is.na(days), 0, days)) %>%
  mutate(countyfips = fips)

write_csv(trials_model, "coviddata.csv")

#### REGRESSION MODELS ####
# negative binomial:
m1 <- glmmTMB(total ~ 1 + 
              POPPCT_URBAN  + 
              log(hospitals + 1) +
              log(cases + 1) + 
              black_aa + 
              white_race + 
              hispanic + 
              poverty +
              age75_plus +
              days + (1|state),
             offset = (log(population)),
             family = nbinom1,
            data = trials_model)
summary(m1)


```


```{r, eval = F}

fit_model <- function(input) {
  
  # manually resample data (with replacement)
  sampled_data <- dat[sample(nrow(dat), replace = TRUE),]
  
  # zero inflated NB model
  m <- zeroinfl(total ~ 
                  POPPCT_URBAN + 
                  log_beds + 
                  insurance +
                  log_case + 
                  black_aa +
                  lths_education + 
                  hispanic +
                  poverty  +
                  days, 
                offset = log(population),
                data = sampled_data)

  # recycled predictions 
  model_table <- t(sapply(names(summary(m)$coefficients$count[,1])[-1], function(var_name){
    delta <- quantile(sampled_data[[var_name]], 
                      p = c(0.1, 0.9), na.rm = TRUE)
    newdata1 <- sampled_data
    newdata1[[var_name]] <- delta[1]
    phat1 <- predict(m, newdata1)
    newdata2 <- sampled_data
    newdata2[[var_name]] <- delta[2]
    phat2 <- predict(m, newdata2)
    diff[[var_name]] <- mean(phat2, na.rm = T)/ mean(phat1, na.rm = T)
    return(diff[[var_name]])
  }))
  return(model_table)
}

set.seed(10)
reps = 10
results <- matrix(NA, reps, length(summary(m)$coefficients$count[,1])-1)
for (i in 1:reps){
  results[i,] <- fit_model(dat)
}
colnames(results) <- names(summary(m)$coefficients$count[,1])[-1]
results <- as.data.frame(results)
results

```


```{r spatial, eval = F}

library(rgdal); library(maptools); library(maps);library(raster);library(spdep)
library(INLA);library(dplyr);library(ggplot2);library(readr);library(ggthemes)
library(labelled); library(ggsci); library(htmlwidgets); library(plotly);
library(grid); library(gridExtra)
library(labelled)

### Preparing the Shapefile ##########

full_state<- shapefile("cb_2018_us_state_500k")
# plot(coordinates(full_state))
# states<-crop(full_state,extent(-175,-55,19,70))
states<-crop(full_state,extent(-175,-55,19,50))
# plot(coordinates(states))
# adding a variable for merging with the case data
states@data<-states@data%>%mutate(statefp=as.numeric(GEOID))
states@data$id<-rownames(states@data)

### Preparing the Case /County_COVID/Data ##########
dat <- read_csv("coviddata.csv") %>%
  mutate(statefp = as.numeric(state),
         log_pop = log(population),
         log_case = log(cases + 1),
         log_hospitals = log(hospitals + 1))
x <- table(dat$countyfips)

### Labeling data for tables ##########
label_frame <- list(
  c("log_pop", "Population"),
  c("log_case", "COVID-19 cases"),
  c("log_hospitals", "Number of hospitals"),
  c("black_aa", "Pct. black"),
  c("lths_education", "Pct. less than HS education"),
  c("POPPCT_URBAN", "Urbanicity score"),
  c("poverty", "Pct. living below poverty line"),
  c("hispanic", "Pct. hispanic"),
  c("days", "Days since first case")
)

# label data
lapply(label_frame, function(x){
  var_label(dat[[x[1]]]) <<- x[2]
})

# make adjacency matrix and add to data
nb.r <- poly2nb(states, queen = T)
mat <- nb2mat(nb.r, style="B",zero.policy=TRUE) 

# -- add state ID that corresponds to the adjacency matrix into the data -- #
StateIDs <- states@data[,c("statefp","id")] %>% 
  mutate(id=as.numeric(id))

dat <- dat %>% 
  left_join(StateIDs) %>%
  mutate(id=as.numeric(id)) %>%
  mutate(log_beds = log(hospital_beds + 1),
         log_cases = log(cases + 1),
         log_pop = log(population))

#### SPATIAL MODELS ####
census_sf <- raw_census %>%
  group_by(GEOID) %>%
  slice(1) %>%
  ungroup() %>% # much faster than distinct
  rename(fips = GEOID) %>%
  select(fips, geometry) %>%
  inner_join(trials_census, by = "fips")

# create contiguity based matrix
coords <- st_coordinates(st_centroid(st_geometry(census_sf)))  
plot(st_geometry(census_sf), border="grey")
census_nb <- poly2nb(census_sf, queen=T)
census_w<-nb2listw(census_nb, style="W", zero.policy = TRUE)

moran.test(census_sf$total/census_sf$population, census_w, 
           alternative = "two.sided",
           zero.policy = TRUE)    
# there is no spatial autocorrelation in # trials/population...
# Estimate: -0.003 and p-value = 0.8... certainly makes my life easier.
```
